services:
  - type: web
    name: chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: GROQ_API_KEY
        sync: false # This means it will be manually set in the Render dashboard 